version: '2.4'

################################################################################
#
# EXAMPLE FILE:
# This docker-compose file contains example services for LND and BTC. This
# file can be used directly to setup your application for use w/ the lnd-engine.
#
# IMPORTANT NOTES:
# - Available ports for a specific service are located in its applicable Dockerfile.
#   However, nothing is bound to the host
# - All cert generation happens within the Dockerfiles
# - /shared directory is used between local services for sharing of public keys
#   however in a production setting, this setup would need to change
#
# The official LND docker setup can be found here:
# https://github.com/lightningnetwork/lnd/tree/master/docker
#
################################################################################

services:
  btcd:
    image: kinesis_btcd:latest
    volumes:
      - shared:/shared
      - bitcoin:/data
    environment:
      # PLEASE modify the user/pass to more secure information as these credentials
      # can be used to directly access your btc instance
      - RPC_USER=kuser
      - RPC_PASS=kpass
      - NETWORK=simnet
      - DEBUG=info
      - DATA_DIR=/data
      - LOG_DIR=/data
      - RPC_KEY=/secure/rpc.key
      - RPC_CERT=/shared/rpc-btc.cert
      - RPC_LISTEN=0.0.0.0
      - MAX_WEB_SOCKETS=100
      # This is set dynamically in the startup scripts
      # TODO: figure out how to dynamically set this variable and prevent it from
      # triggering warnings
      - "MINING_ADDRESS=$MINING_ADDRESS"
    # Only needed for development
    ports:
      - '18555:18555'
      - '18556:18556'
    entrypoint: ["./start-btcd.sh"]

  lnd_btc:
    image: kinesis_lnd_btc:latest
    environment:
      # PLEASE modify the user/pass on your BTCD node to more secure information
      # as these credentials can be used to directly access your btcd instance
      - RPC_USER=kuser
      - RPC_PASS=kpass
      - RPC_HOST=docker.for.mac.host.internal
      - RPC_CERT_PATH=/shared/rpc.cert
      - ADMIN_MACAROON=/shared/lnd-engine-admin-btc.macaroon
      - READ_ONLY_MACAROON=/shared/lnd-engine-readonly-btc.macaroon
      - INVOICE_MACAROON=/shared/lnd-engine-invoice-btc.macaroon
      - TLS_CERT_PATH=/shared/lnd-engine-tls-btc.cert
      - TLS_KEY_PATH=/secure/lnd-engine-tls-btc.key
      - NETWORK=simnet
      - CHAIN=bitcoin
      - NODE=btcd
      - DEBUG=info
      - RPC_LISTEN=0.0.0.0:10009
      - LISTEN=0.0.0.0:10111
      # This address is for development only. You must change this to a
      # tld to use in a production setting
      - EXTERNAL_ADDRESS=docker.for.mac.host.internal:10111
      - REST_LISTEN=0.0.0.0:8101
      - DATA_DIR=/data
      - LOG_DIR=/data
    volumes:
      - 'shared:/shared'
      - 'lnd:/data'
    entrypoint: ["./start-lnd.sh"]

volumes:
  shared:
  bitcoin:
  lnd:
