version: '2.4'

################################################################################
#
# NOTE: This docker-compose only contains LND setup for BTC. LTC and other coins
# are not currently implemented for the kinesis exchange
#
# The official LND docker setup can be found here:
# https://github.com/lightningnetwork/lnd/tree/master/docker
#
################################################################################

services:
  repl:
    image: node:8
    working_dir: '/home/app'
    volumes:
      - './:/home/app'
      - 'shared:/shared/'
    environment:
      # - GRPC_VERBOSITY=INFO
      # - GRPC_TRACE=all
      - NODE_PATH=.
      - GRPC_SSL_CIPHER_SUITES=HIGH+ECDSA
    networks:
      - lnd

  btcd:
    build:
      context: ./docker
      dockerfile: btcd/Dockerfile
    volumes:
      - shared:/shared
      - bitcoin:/data
    environment:
      - RPC_USER=kuser
      - RPC_PASS=kpass
      - NETWORK=simnet
      - DEBUG=info
      - DATA_DIR=/data
      - LOG_DIR=/data
      - RPC_KEY=/secure/rpc.key
      - RPC_CERT=/shared/rpc.cert
      - RPC_LISTEN=0.0.0.0
      # This is set dynamically in the startup scripts
      # TODO: figure out how to dynamically set this variable and prevent it from
      # triggering warnings
      - "MINING_ADDRESS=$MINING_ADDRESS"
    expose:
      - '8333' # mainnet p2p
      - '8444' # mainnet rpc
      - '18333' # testnet p2p
      - '18334' # testnet rpc
      - '18555' # simnet p2p
      - '18556' # simnet rpc
      - '28901' # segnet p2p
      - '28902' # segnet rpc
    networks:
      lnd:
        aliases:
          - blockchain
          - rpcserver
    entrypoint: ["./start-btcd.sh"]

  lnd_btc:
    build:
      context: ./docker
      dockerfile: lnd/Dockerfile
    environment:
      - RPC_USER=kuser
      - RPC_PASS=kpass
      - RPC_HOST=blockchain
      - RPC_CERT_PATH=/shared/rpc.cert
      - ADMIN_MACAROON=/shared/lnd-engine-admin.macaroon
      - READ_ONLY_MACAROON=/shared/lnd-engine-readonly.macaroon
      - INVOICE_MACAROON=/shared/lnd-engine-invoice.macaroon
      - TLS_CERT_PATH=/shared/lnd-engine-tls.cert
      - TLS_KEY_PATH=/secure/lnd-engine-tls.key
      - NETWORK=simnet
      - CHAIN=bitcoin
      - DEBUG=info
      - RPC_LISTEN=0.0.0.0:10009
      - LISTEN=0.0.0.0:10111
      - REST_LISTEN=0.0.0.0:8101
      - DATA_DIR=/data
      - LOG_DIR=/data
      - NODE=btcd
    networks:
      - lnd
    volumes:
      - 'shared:/shared'
      - 'lnd:/data'
    expose:
      - '10009'
      - '10111'
      - '8101'
    entrypoint: ["./start-lnd.sh"]

volumes:
  shared:
  bitcoin:
  lnd:

networks:
  lnd:
